glynt/apps/lawyer/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from glynt.apps.lawyer.views import (LawyerListView, LawyerLiteProfileView,
                                     LawyerProfileSetupView, LawyerProfileView,
                                     LawyerContactView,)


urlpatterns = patterns('',
    url(r'^welcome/$', login_required(TemplateView.as_view(template_name='lawyer/welcome.html')), name='welcome'),
    url(r'^invite/$', login_required(TemplateView.as_view(template_name='lawyer/invite.html')), name='invite'),
    url(r'^profile/setup/$', login_required(LawyerProfileSetupView.as_view()), name='setup_profile'),

    url(r'^(?P<slug>.+)/contact/$', login_required(LawyerContactView.as_view()), name='contact'),
    url(r'^(?P<slug>.+)/lite/$', LawyerLiteProfileView.as_view(), name='profile_lite'),
    url(r'^(?P<slug>.+)/$', LawyerProfileView.as_view(), name='profile'),
    url(r'^$', LawyerListView.as_view(), name='list'),
)

glynt/apps/project/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from .views import (ProjectView, CreateProjectView, CloseProjectView, 
                    ReOpenProjectView,
                    ProjectCategoryView,
                    LawyerContactProjectView,)

urlpatterns = patterns('',
    url(r'^create/$', login_required(CreateProjectView.as_view()), name='create'),

    url(r'^(?P<slug>.+)/(?P<lawyer>.+)/project-contact/$', login_required(LawyerContactProjectView.as_view()), name='project_contact'),

    url(r'^(?P<slug>.+)/category/$', login_required(ProjectCategoryView.as_view()), name='category'),

    url(r'^(?P<slug>.+)/close/$', login_required(CloseProjectView.as_view()), name='close'),
    url(r'^(?P<slug>.+)/re-open/$', login_required(ReOpenProjectView.as_view()), name='re-open'),
    url(r'^(?P<slug>.+)/$', login_required(ProjectView.as_view()), name='project'),
)

glynt/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

handler500 = 'glynt.apps.default.views.handler500'

def _v1_api():
    from glynt.apps.api.v1 import V1_INTERNAL_API
    return V1_INTERNAL_API.urls


urlpatterns = patterns('',
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # User Switcher
    url(r'^impersonate/', include('impersonate.urls')),

    # Api
    # v2 rest_framework
    url(r'^api/v2/', include('glynt.apps.api.v2', namespace='api_v2')),
    # v1 (tastypie to be depreciated)
    url(r'^api/', include(_v1_api(), namespace='api')),

    # image upload and crop
    url(r'^ajax-upload/', include('cicu.urls')),

    # Invite to join
    url(r'^invite/', include('public.invite.urls', namespace='invite')),

    # Accounts & Registration
    url(r'', include('social_auth.urls')),
    url(r'^accounts/', include('userena.urls')),
    url(r'^client/', include('glynt.apps.client.urls', namespace='client')),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),

    # Activity stream
    url('^activity/', include('actstream.urls')),

    # Crocdoc Webhook Callbacks
    url('^crocdoc/', include('glynt.apps.crocdoc.urls', namespace='crocdoc')),

    # Customers
    url(r'^customers/', include('glynt.apps.customer.urls', namespace='customer')),

    # lawyers
    url(r'^lawyers/', include('glynt.apps.lawyer.urls', namespace='lawyer')),

    # Project app
    url(r'^projects/', include('glynt.apps.project.urls', namespace='project')),

    # ToDo checklist items
    url(r'^todo/', include('glynt.apps.todo.urls', namespace='todo')),

    # Transaction
    url(r'^transact/', include('glynt.apps.transact.urls', namespace='transact')),

    # Comments
    url(r'^comments/', include('fluent_comments.urls')),

    # Dashboard
    url(r'^dashboard/', include('glynt.apps.dashboard.urls', namespace='dashboard')),

    # The public site and theme
    url(r'^', include('public.urls', namespace='public')),

    # favicon & Utils
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': {}}),  # @TODO need to set this up with alex
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),  # @TODO need to set this up with alex
    url(r'^favicon\.ico/$', RedirectView.as_view(url='%simg/favicon.ico' % settings.STATIC_URL)),  # @TODO need to set this up with alex
)


if settings.DEBUG or settings.PROJECT_ENVIRONMENT == 'dev':
    urlpatterns +=  patterns('', url(r'', include('debug_toolbar_user_panel.urls')))
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

glynt/apps/project/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django_extensions.db.fields import CreationDateTimeField, ModificationDateTimeField

from uuidfield import UUIDField
from jsonfield import JSONField

from . import PROJECT_STATUS, PROJECT_LAWYER_STATUS
from .managers import DefaultProjectManager, ProjectLawyerManager
from .mixins import (ProjectCategoriesMixin,
                     ProjectRulezMixin,
                     ProjectActivityMixin)

from rulez import registry as rulez_registry


class Project(ProjectCategoriesMixin, ProjectRulezMixin, ProjectActivityMixin, models.Model):
    """ Base Project object
    Stores initial project details
    """
    _PROJECT_STATUS = PROJECT_STATUS

    uuid = UUIDField(auto=True, db_index=True)
    customer = models.ForeignKey('customer.Customer')
    company = models.ForeignKey('company.Company')
    transactions = models.ManyToManyField('transact.Transaction')
    lawyers = models.ManyToManyField('lawyer.Lawyer', blank=True, through='project.ProjectLawyer')
    participants = models.ManyToManyField('auth.User', blank=True)
    data = JSONField(default={})
    status = models.IntegerField(choices=PROJECT_STATUS.get_choices(), default=PROJECT_STATUS.new, db_index=True)
    date_created = CreationDateTimeField()
    date_modified = ModificationDateTimeField()

    objects = DefaultProjectManager()

    def __unicode__(self):
        return u'Project for {company_name}'.format(company_name=self.data.get('company_name', ''))

    @staticmethod
    def content_type():
        """
        Static method used to access the content type of projects
        """
        return ContentType.objects.get_for_model(Project)

    @property
    def content_type_id(self):
        return Project.content_type().pk

    @property
    def pusher_id(self):
        return str(self.uuid)

    @property
    def primary_lawyer(self):
        return self.get_primary_lawyer()

    @property
    def has_lawyer(self):
        from glynt.apps.project.models import ProjectLawyer
        return ProjectLawyer.objects.assigned(project=self).count() > 0

    @property
    def is_open(self):
        return self._PROJECT_STATUS.open == self.status

    @property
    def is_closed(self):
        return self._PROJECT_STATUS.closed == self.status

    @property
    def is_new(self):
        return self._PROJECT_STATUS.new == self.status

    @property
    def transaction_slugs(self):
        return [t.slug for t in self.transactions.all()]

    @property
    def transaction_types(self):
        return [t.title for t in self.transactions.all()]

    @property
    def tx_range(self):
        return ','.join(self.transaction_slugs)

    @property
    def display_status(self):
        return self._PROJECT_STATUS.get_desc_by_value(self.status)

    @property
    def project_statement(self):
        return self.data.get('project_statement', None)

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('dashboard:project', kwargs={'uuid': str(self.uuid)})

    def get_checklist_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('dashboard:checklist', kwargs={'uuid': str(self.uuid)})

    def checklist(self):
        """
        Load all of the projects transaction types
        and extract their bunch classes (based on yml files)
        """
        checklist_items = []

        for t in self.transactions.all():
            checklist_items += t.checklist()

        return checklist_items

    def get_primary_lawyer(self):
        from glynt.apps.project.models import ProjectLawyer
        try:
            primary_lawyer_join = ProjectLawyer.objects.assigned(project=self)[0]
            return primary_lawyer_join.lawyer
        except IndexError:
            return None

    def notification_recipients(self):
        """
        provide access to the customer, the lawyer
        ### not yet ### as well as any user associated with the customers company ## end not yet ##
        """
        return self.participants.all()


class ProjectLawyer(models.Model):
    """
    The customised variation of a generic m2m model
    msut be named ProjectLawyer(s) <-- this is not noraml for django
    """
    _LAWYER_STATUS = PROJECT_LAWYER_STATUS

    project = models.ForeignKey('project.Project')
    lawyer = models.ForeignKey('lawyer.Lawyer')
    status = models.IntegerField(choices=_LAWYER_STATUS.get_choices(), default=_LAWYER_STATUS.potential, db_index=True)

    objects = ProjectLawyerManager()

    class Meta:
        db_table = 'project_project_lawyer'

    @property
    def display_status(self):
        return self._LAWYER_STATUS.get_desc_by_value(self.status)

    def notification_recipients(self):
        """
        """
        return [self.project.customer.user, self.lawyer.user]

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('project:project_contact', kwargs={'slug': self.project.uuid, 'lawyer': self.lawyer.user.username})


"""
The signal connections are handled here as the signals are imported a number of
the imports in this file will cause circular imports
"""
from .signals import (on_project_created,
                      on_save_ensure_user_in_participants, 
                      on_lawyer_assigned,
                      on_project_categories_sort_updated,
                      on_project_profile_is_complete,
                      lawyer_on_save_ensure_participants,
                      lawyer_on_delete_ensure_participants,)


rulez_registry.register("can_read", Project)
rulez_registry.register("can_edit", Project)
rulez_registry.register("can_delete", Project)

glynt/apps/project/forms.py
# -*- coding: UTF-8 -*-
from django import forms
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify

from parsley.decorators import parsleyfy
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Field, Layout, Submit

from .models import Project

from public.forms import ContactForm


def _default_intro_text():
    return "The following lawyers are interested in working with you. \r\
\r\
At this stage we recommend speaking with one or more of the lawyers below. Once you are happy to proceed with a particular lawyer, you can engage them from your Project Overview.\r\
\r\
If you have any questions, please contact your project manager Yael Citro at yael@lawpal.com or (415) 691 6069."


@parsleyfy
class AdminMatchingEmailCustomContentForm(forms.Form):
    intro = forms.CharField(label='Introductory Content', initial=_default_intro_text(), help_text='Your intro text', required=True, widget=forms.Textarea)


@parsleyfy
class ContactUsForm(ContactForm):
    """
    Form to handle contacting us when we don't offer the service required
    """

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.form_id = 'contact-us-form'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('public:contact_us')

        self.helper.add_layout(Layout(
            Div(
                Field('name'),
                Field('message'),
                Field('email'),
                css_class='modal-body'
            ),
            Div(
                Submit('send', 'Send', css_id='send-contact-us-modal'),
                css_class='modal-footer',
            ),
        ))

        super(ContactUsForm, self).__init__(*args, **kwargs)


class CreateProjectForm(forms.Form):
    intake_data = forms.CharField(widget=forms.HiddenInput)
    transaction_type = forms.CharField(widget=forms.HiddenInput)


@parsleyfy
class ProjectCategoryForm(forms.ModelForm):
    """
    Form used to add/edit categories to projects
    """
    data = forms.CharField(required=True, widget=forms.HiddenInput)
    category = forms.CharField(required=True)

    class Meta:
        model = Project
        fields = ('data',)

    def __init__(self, *args, **kwargs):
        project_uuid = kwargs.pop('project_uuid')
        self.original_category = kwargs.pop('original_category')

        self.message = None
        self.added_message = 'Added category "{category}"'
        self.modified_message = 'Modified category "{original_category}"" to be "{category}"'

        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.form_id = 'project-category'
        self.helper.form_method = 'post'

        self.helper.form_action = reverse('project:category', kwargs={'slug': project_uuid})

        self.helper.add_layout(Layout(
            Div(
                'General',
                'category',
                css_class='modal-body'
            )
        ))

        super(ProjectCategoryForm, self).__init__(*args, **kwargs)

    def clean_data(self):
        """
        just return the data field without validation or cleaning
        """
        return self.instance.data

    def clean_category(self):
        """
        clean logic for adding new categories
        should probably be a mixin
        """
        category = self.cleaned_data.get('category', None)
        # Used in the view
        self.category = category
        self.category_slug = slugify(category)

        categories = self.instance.categories

        # delete the old original category if present
        if self.original_category not in categories:
            # add
            if category is None:
                raise forms.ValidationError('Category cannot be None')
            else:
                # append new cat if not None
                categories.append(category)
                self.message = self.added_message.format(category=category)
        else:
            # edit
            categories.remove(self.original_category)
            # set the message
            self.message = self.modified_message.format(original_category=self.original_category, category=category)

        # set the instance categories to our updated
        # ensure uniquness by convert to set then back to list
        # cant use set as set loses sort order which is important here
        self.instance.categories = categories

        return category

    def save(self, **kwargs):
        if self.cleaned_data.get('category', None) in self.instance.categories:
            self.instance.save(update_fields=['data'])

glynt/apps/project/templates/project/create.html
{% extends 'base.html' %}{% load url from future %}
{% load i18n crispy_forms_tags company_tags transaction_tags %}

{% block head %}
    {{ wizard.form.media }}
{% endblock %}

{% block css %}
    <link href="{{ STATIC_URL }}css/theme/transaction.css" rel="stylesheet" charset="utf-8"/>
{% endblock %}

{% block page_title %}
Select a Transaction
{% endblock %}

{% block prebody %}
<div class="megatron">
    <div class="container">
        <h2><i class="glyphicon glyphicon-briefcase" style="padding: 27px 28px 22px 28px;"></i></h2>
        <h1>What do you need?</h1>
        <h3>Pick a package or tell us what you need.</h3>
    </div>
</div>
{% endblock %}

{% block body %}
<div class="container packages-view">
    <div class="row">
        <div class="col col-lg-6">
            {% transactions transaction='CS' %}
            {% transactions transaction='SF' %}
        </div>
        <div class="col col-lg-6">
            {% transactions transaction='ES' %}

            <div id="custom-package" class="callout callout-info clearfix">
                <p class="lead pull-right">-</p>
                <h4>Need something else?</h4>
                <p>Just give us the details and we will get back to you ASAP.</p>
                <p><button id="contact-us-btn" class="btn btn-info custom-package-button" data-toggle="modal" data-target="#custom-package-modal" data-is_ajax="false"><i class="icon-envelope icon-white"></i> Contact us</button></p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col col-lg-12">
            <button id="continue" class="btn btn-success btn-huge pull-right">{% trans "Continue" %}</button>
        </div>
    </div>

    <form id="transaction-form" method="POST">
        {% csrf_token %}
        {{ form }}
    </form>
</div>
{% endblock %}

{% block js %}
<script>
'use strict';
var selected_transactions = [];

function transaction_business_logic(element) {
    var elm = $(element).attr('data-transaction');
    if (elm === 'SF') {
        transaction_deselection($('.transaction-choice[data-transaction="ES"] .btn'));
    } else if (elm === 'ES') {
        transaction_deselection($('.transaction-choice[data-transaction="SF"] .btn'));
    }
    transaction_selection(element.find('.btn'));
}

function transaction_selection(element) {
    element.addClass('active btn-success').html('<i class="icon-ok icon-white"></i> Package added');
    element.parent().parent().addClass('callout-success');
    selected_transactions.push(element.parent().parent().attr('data-transaction'));
}

function transaction_deselection(element) {
    element.removeClass('active btn-success').html('<i class="icon-plus icon-white"></i> Add package');
    element.parent().parent().removeClass('callout-success');
    var index = selected_transactions.indexOf(element.parent().parent().attr('data-transaction'));
    if (index > -1) {
        selected_transactions.splice(index, 1);
    }
}

function select_active_transactions() {
    var actives = $('#id_transaction_type').attr('value');

    if (actives && actives.length > 0) {
        var split = actives.split(",");

        for (var i = 0; i < split.length; i++) {
            var elm = $('.transaction-choice[data-transaction="' + split[i] + '"]');
            transaction_business_logic(elm);
        }
    }
}

$(document).ready(function () {

    select_active_transactions();

    $('.transaction-choice .btn').on('click', function () {
        var elm = $(this);
        if (!$(this).hasClass('active')) {
            // Check if Note financing and disable Equity financing if true (and visa versa)
            transaction_business_logic(elm.parent().parent());
        } else {
            transaction_deselection(elm);
        }
    });

    $('#continue').on('click', function () {
        if (selected_transactions.length > 0) {
            $('#id_transaction_type').attr('value', selected_transactions);
            $('form#transaction-form').submit();
        } else {
            $('#instructions').addClass('animated shake');
            window.setTimeout(function () {
                $('#instructions').removeClass()
            }, 1300);
        }
    });

    /**
    * Submit handler for the contact-us form
    * which is used for custom package requests
    */
    $('form#contact-us-form').parsley();
    $('form#contact-us-form').on('submit', function(event) {
        event.preventDefault();

        var form = $(this);
        GlyntJsMessages.clear = true;

        if ( form.parsley( 'isValid' ) ) {

            $.ajax({
                type: 'POST',
                url: form.attr('action'),
                data: form.serialize()
            })
            .success(function(data) {
                GlyntJsMessages.add_message('Thanks, your message has been sent');
            })
            .error(function(data, textStatus, jqXHR) {
                // validation errors handled by parsley, so just log
                // this to the console
                console.log(data.responseText);
                GlyntJsMessages.add_message('Sorry, an error occurred. Please try again or contact founders@lawpal.com');
            })
            .complete(function() {
                $('#custom-package-modal').modal('hide');
                GlyntJsMessages.show();
            });
        }

    });
});
</script>
{% endblock %}

{% block modals %}
<!-- Modal -->
<div id="custom-package-modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Contact Us</h4>
            </div>

            {% crispy contact_form %}

        </div>
    </div>
</div>
{% endblock %}

glynt/apps/project/templates/project/lawyer_contact.html
{% load url from future %}{% load comments fluent_comments_tags %}
{% csrf_token %}
{% block css %}
    <link href="{{ STATIC_URL }}css/theme/lawyer-profile.css" rel="stylesheet" charset="utf-8" />
    <style>
        .media-body #btn-save_comment {float:right; padding:10px 10px 10px 10px;margin-right:38px;}
    </style>
{% endblock %}

<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

{% if request.user.profile.is_lawyer %}
    <!-- show customer detail -->
    {% with primary_join.project.customer as customer %}
    <div id="hero-mini">
        <div class="container container-main">
            <!-- starts carousel -->
            <div class="row profile-details">
                <div class="col col-sm-4 text-center">
                    <div class="avatar text-center">
                        <img class="img-rounded" src="{{ customer.profile_photo }}" alt="{{ customer.user.get_full_name|default:customer.user.username }}" />
                    </div>
                </div>
                <div class="col col-sm-8">
                    <h1>{{ customer.user.get_full_name|default:customer.user.username }}</h1>
                    <strong>Company</strong> {{ customer.data.company }}<br/>
                    <strong>Phone.</strong> {{ customer.data.telephone }}
                </div>
            </div>
        </div>
    </div>
    {% endwith %}

{% else %}
    <!-- show lawyer info -->
    <div id="hero-mini">
        <div class="container container-main">
            <!-- starts carousel -->
            <div class="row profile-details">
                <div class="col col-sm-4 text-center">
                    <div class="avatar text-center">
                        <img src="{{ lawyer.profile_photo }}" alt="{{ lawyer.user.get_full_name|default:lawyer.user.username }}" />
                    </div>
                </div>
                <div class="col col-sm-8">
                    <h1>{{ lawyer.user.get_full_name|default:lawyer.user.username }}</h1>
                    <div class="firm">
                        <h2 style="text-info">
                            {% if lawyer.position %}{{ lawyer.position }}{% endif %}{% if lawyer.firm_name %} <span>at</span> {{ lawyer.firm_name }}{% endif %}
                        </h2>
                        <p>{{ lawyer.data.summary }}</p>
                    </div>
                    <div id="buttons">
                        {% comment %}
                        {% if join.status == PROJECT_LAWYER_STATUS.potential %}
                            <button data-engage="{{ join.pk }}" data-status="{{ PROJECT_LAWYER_STATUS.assigned }}" class="btn btn-success">Engage {{ lawyer.user.get_full_name|default:lawyer.user.username }}</button>
                        {% endif %}
                        {% endcomment %}
                        <a href="{% url 'lawyer:profile_lite' slug=lawyer.user.username %}" data-toggle="modal" data-target="#overview-modal" data-is_ajax="true" class="btn btn-info">View Profile</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}

<hr/>

<!-- Comments -->
{% render_comment_form for primary_join %}
<br />
{% render_comment_list for primary_join %}
<!-- End Comments -->

glynt/apps/project/templates/project/project_detail.html
{% extends "comments/base.html" %}{% load comments project_tags fluent_comments_tags %}

{% block page_title %}Engagement Request{% endblock %}

{% block breadcrumb %}
<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li><a href="{% url 'project:list' %}">Inbox</a> <span class="divider">/</span></li>
    <li class="active">{% if user.profile.is_customer %}Request to: {{ object.lawyer.user.get_full_name }}{% else %}Request from: {{ object.customer.user.get_full_name }}{% endif %}</li>
</ul>
{% endblock %}

{% block content %}
<div class="row">
    <div class="span8">
        <div class="alert engagement-status">
            <span>Request status: <strong>{{ object.status }}</strong></span>
        </div>
        <h3 class="engage-detail-title">
            {% if user.profile.is_customer %}
                Request to: {{ object.lawyer.user.get_full_name }}
            {% else %}
                Request from: {{ object.customer.user.get_full_name }}
            {% endif %}
        </h3>
        <span>{{ object.date_created }}</span>
        <hr />
        {% render_comment_form for object %}
        <hr>
        <h5>Conversation history (most recent at the top)</h5>

        {% render_comment_list_reversed for object %}

        {#% engagement_intro engagement=object %#}
    </div>
    <div class="span4 side-info-container">
        <div class="well">
            {% if user.profile.is_customer %}
            <div class="profile-card" data-username="{{ object.lawyer.user.username }}">&nbsp;</div>
            {% else %}
            <div class="startup-profile-card" data-username="{{ object.startup.slug }}">&nbsp;</div>
            <hr/>
            <div class="profile-card" data-username="{{ object.customer.user.username }}">&nbsp;</div>
            {% endif %}
        </div>

        <span id="engagement-status-controls">
        {% if object.is_closed %}
            <a href="#mod-engagement-status" data-toggle="modal" class="initial-lead"><i class="icon icon-ok"></i> Re-open this Lead</a>
        {% else %}
            <a href="#mod-engagement-status" data-toggle="modal" class="close-lead"><i class="icon icon-remove"></i> Close this Lead</a>
        {% endif %}
        </span>

        <div id="mod-engagement-status" class="modal hide fade" role="dialog" aria-labelledby="close engagement" aria-hidden="true">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3>Warning</h3>
            </div>
            <div class="modal-body">
                {% if object.is_closed %}
                    <p>You are sure you want to re-open this lead?</p>
                {% else %}
                    <p>You are sure you want to close this lead?</p>
                {% endif %}
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" aria-hidden="true" class="btn secondary">No</button>
                <a href="#close-engagement" id="btn-confirm-close-engagement" data-url="{% if object.is_closed %}{% url 'project:re-open' slug=object.slug %}{% else %}{% url 'project:close' slug=object.slug %}{% endif %}" class="btn btn-danger">Yes</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}fluent_comments/css/ajaxcomments.css" />
<script type="text/javascript" src="{{ STATIC_URL }}fluent_comments/js/ajaxcomments.js"></script>
<script>
/**
* Setup the fluent-comments comment_controls
* to determine setup and useability
* @LawPal contributed this functionality
**/
var COMMENT_CONTROLS = {
    'is_reversed': true
    ,'scroll_to_comment': false
};

$(document).ready(function(){
    $('#btn-confirm-close-engagement').live('click', function(event){
        event.preventDefault()
        var csrf_token = $('input[name=csrfmiddlewaretoken]').val()
        $.ajax({
            type: 'POST'
            ,url: $(this).attr('data-url')
            ,data: {'csrfmiddlewaretoken':csrf_token}
            ,success: function(data, status) {
                GlyntJsMessages.add_message(data.message);
                $('#engagement-status-controls').fadeOut('slow');
            }
            ,error: function(jsdata, data, status) {
                GlyntJsMessages.add_message(data.message, 'error');
            }
            ,complete: function(){
                $("#mod-engagement-status").modal('hide');
                GlyntJsMessages.show();
            }
        });
    });
});
</script>
{% endblock %}

glynt/apps/project/templates/project/project_list.html
{% extends "comments/base.html" %}{% load url from future %}{% load i18n project_tags %}

{% block breadcrumb %}
<ul class="breadcrumb">
    <li><a href="/">Home</a> <span class="divider">/</span></li>
    <li class="active">Inbox</li>
</ul>
{% endblock %}

{% block content %}

    {% if invalid_page %}

    <p>{% trans "Sorry, this page number is invalid." %}</p>

    {% else %}
        {% if object_list %}
            <ul id="engagement-list" class="message-list">
                {% for message in object_list %}
                <li class="engage-status-{{ message.status|lower }}" data-pk="{{ message.pk }}" data-url="{{ message.get_absolute_url }}">
                    <a href="{{ message.get_absolute_url }}">
                        {% if user.profile.is_customer %}
                        <span class="profile-card" data-template="mini" data-username="{{message.lawyer.user.username}}">
                            <img src="{{ STATIC_URL }}img/default_avatar.png" class="avatar">
                        </span>
                        <span class="message-sender">{{ message.lawyer.user.get_full_name }} @ {{ message.lawyer.firm_name }}</span>
                        <span class="message-date">{{ message.date_created|date:"d M" }}</span>
                        <span class="label engage-status engage-status-{{ message.status|lower }}">{{ message.status }}</span>
                        {% else %}
                        <span class="profile-card" data-template="mini" data-username="{{message.customer.user.username}}"></span>
                        <span class="message-sender">{{ message.startup }} @ {{ message.customer.user.get_full_name }}</span>
                        <span class="message-date">{{ message.date_created|date:"d M" }}</span>
                        <span class="label engage-status engage-status-{{ message.status|lower }}">{{ message.status }}</span>
                        {% endif %}
                    </a>
                </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>You currently have no Engagements. Why not try searching for a Lawyer on the <a href="{% url 'lawyer:list' %}">marketplace</p>
        {% endif %}

    {% endif %}

{% endblock content %}